-- migrate:up
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  kakao_id BIGINT NOT NULL,
  email VARCHAR(255) NULL,
  nickname VARCHAR(255) NULL,
  profile_image VARCHAR(255) NULL,
  bio VARCHAR(255) NULL,
  point DECIMAL (10, 2) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE users;